// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CwP_k6v-49MV6FzzrsgCX0a2F5WlkaY',
    appId: '1:998852566932:web:a87a43c4bda86272bdb981',
    messagingSenderId: '998852566932',
    projectId: 'storeappdamojf',
    authDomain: 'storeappdamojf.firebaseapp.com',
    databaseURL: 'https://storeappdamojf-default-rtdb.firebaseio.com',
    storageBucket: 'storeappdamojf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwi4qKcVuhX6ltZYSadDsosQb4HnVrGn0',
    appId: '1:998852566932:android:53f837bfb672fa89bdb981',
    messagingSenderId: '998852566932',
    projectId: 'storeappdamojf',
    databaseURL: 'https://storeappdamojf-default-rtdb.firebaseio.com',
    storageBucket: 'storeappdamojf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAMN5hFFIhwiVNZAi2rXF4e2b9W6r3u2a4',
    appId: '1:998852566932:ios:408b568a5adf63e2bdb981',
    messagingSenderId: '998852566932',
    projectId: 'storeappdamojf',
    databaseURL: 'https://storeappdamojf-default-rtdb.firebaseio.com',
    storageBucket: 'storeappdamojf.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.juanf.storeappv2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAMN5hFFIhwiVNZAi2rXF4e2b9W6r3u2a4',
    appId: '1:998852566932:ios:408b568a5adf63e2bdb981',
    messagingSenderId: '998852566932',
    projectId: 'storeappdamojf',
    databaseURL: 'https://storeappdamojf-default-rtdb.firebaseio.com',
    storageBucket: 'storeappdamojf.firebasestorage.app',
    iosBundleId: 'co.edu.unab.damo.juanf.storeappv2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8CwP_k6v-49MV6FzzrsgCX0a2F5WlkaY',
    appId: '1:998852566932:web:546c3c3645bb471ebdb981',
    messagingSenderId: '998852566932',
    projectId: 'storeappdamojf',
    authDomain: 'storeappdamojf.firebaseapp.com',
    databaseURL: 'https://storeappdamojf-default-rtdb.firebaseio.com',
    storageBucket: 'storeappdamojf.firebasestorage.app',
  );

}